Allow to install nokogiri 1.11 rc version
It fixes the following error:

  ERROR: Error installing
  C:/td-agent-4.0.0~rc1/td-agent/downloads/plugin_gems/26-fluent-plugin-windows-eventlog-0.5.4.gem:
  The last version of nokogiri (>= 1.10, < 1.12) to support your Ruby
  & RubyGems was 1.10.9. Try installing it with `gem install nokogiri
  -v 1.10.9` and then running the current command again nokogiri
  requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is
  2.7.1.83.  rake aborted!

Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>